### ISSUE TITLE
Incorrect work of `fmin`

### ISSUE THREAD

**Issue by ladisgin** [UnitTestBot/klee#61]
Moved from https://github.com/UnitTestBot/UTBotCpp/issues/526

Consider the following test case:

```cpp
#include "klee/klee.h"
#include <math.h>
#include <assert.h>

int main() {
    double a = 0.0, b = NAN;

    if (fmin(a, b) == a) {
        return 1;
    } else {
        assert(0);
        return 2;
    }
}
```

According to the `fmin` specification we should return 1, but instead assertion fails in another branch during KLEE execution (you can check this by running via KLEE and compiled elf).

**Comment by S1eGa** [comment]
Resolved by [commit](https://github.com/UnitTestBot/klee/commit/9406351fa133920e003202873b7718ec47271dee).
